image: alpine

before_script:
  - echo "Install deps"
  - apk add --update make wget bash
   
test1:
  stage: test
  script:
    - bash -c "make bash"
    - bash -c "make vim"
    - bash -c "make gitconfig"
    - bash -c "make awesome"
    - bash -c "make x"
    - bash -c "make privacy"
    - bash -c "make hosts"
