image: debian

before_script:
  - echo "Install deps"
  - apt install -yqq --no-install-recommends make wget
    
   
test1:
  stage: test
  script:
    - make bash
    - make vim
    - make gitconfig
    - make awesome
    - make x
    - make privacy
    - make hosts
