image: alpine

before_script:
  - echo "Install deps"
  - apk add --update make wget
   
test1:
  stage: test
  script:
    - make bash
    - make vim
    - make gitconfig
    - make awesome
    - make x
    - make privacy
    - make hosts
