" commands
set showcmd

set nocompatible

" syntax
syntax on
filetype plugin indent on
set hlsearch
set incsearch
set autoindent
set background=dark

" position
set mouse=a
set ruler
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" tabstop
set tabstop=2
set shiftwidth=2
set expandtab
set smarttab

for f in split(glob('~/.vim/f0i/*'), '\n')
  exe 'source' f
endfor

set ttymouse=sgr
