# Path to your oh-my-zsh configuration.
ZSH=$HOME/config/zsh/ohmyzsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="random"
ZSH_THEME="josh"

alias wq="clear"
alias whois='whois --verbose -H'
alias man='man -a'
alias presentation="$TERMINAL -fn 'xft:DejaVu Sans Mono-15'"
alias presentation-white="presentation -bg white -fg black"
alias wifi-status="iwconfig 2>/dev/null|grep Signal|sed 's/^\s*//'||echo No Signal"
alias bmplayer="mplayer -ao alsa:device=bluetooth"
alias qr='ttyqr -b'
alias v='vim'
alias g='git'
alias m='mutt'
alias tunlr='cp /etc/resolv.conf.tunlr /etc/resolv.conf'
alias rm="echo -n Delete\! CTRL-C to cancel, enter to delete\!;read&&rm"

alias namp='sl'
alias qw='sl'
alias commit-bs="git commit -a -m \`curl -s -L http://whatthecommit.com/index.txt\`"


# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ./ohmyzsh/plugins/*)
# Custom plugins may be added to ./ohmyzsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(gitfast)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

bindkey "[D" backward-word
bindkey "[C" forward-word
