#!/bin/bash

#shortcuts
alias v='nvim'
alias vim='nvim'
alias g='git'
alias m='mutt'
alias l='ls'
alias ff='firefox'

alias qr='ttyqr -b'
alias vless='vimpager'

alias cd_='cd "$_"'
alias cd-='cd "$OLDPWD"'
alias cdback='cd "$OLDPWD"'
alias mkdir_='mkdir -p "$_"'
alias echo-='echo "$OLDPWD"'
alias echo_='echo "$_"'
alias wget_='wget "$_"'
alias vim_='vim "$_"'
alias cat_='cat "$_"'
alias ff_='firefox "$_"'
alias ._='. "$_"'
alias ls_='ls "$_"'
alias gqview_='gqview "$_"'
alias find_='find "$_"'

alias cd*='cd */'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'

#params
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias rm="echo -n Delete\! CTRL-C to cancel, enter to delete\!;read&&rm"
alias whois='whois --verbose -H'
alias man='man -a'
alias mplayer-loud='mplayer -softvol -softvol-max 1000 −af volume=10.1:0'
alias skype='apulse32 skype'

#typos
alias namp='nmap'
alias qw='wq'
alias sl='ls'
alias ks='ls'
alias cd..='cd ..'
alias mplayer*='mplayer *'

#others
alias presentation="$TERMINAL -fn 'xft:DejaVu Sans Mono-15'"
alias presentation-white="$TERMINAL -fn 'xft:DejaVu Sans Mono-15' -bg white -fg black"

alias wifi-status='netctl list | grep "*";iwconfig 2>/dev/null|grep Signal|sed "s/^\s*//";[ $? -ne 0 ]&&echo No Signal'
alias wifi='netctl switch-to'
alias bmplayer="mplayer -ao alsa:device=bluetooth"
alias exif-remove-rotation="exiftool -overwrite_original -m -exif:Orientation=1 -n"

alias tunlr='cp /etc/resolv.conf.tunlr /etc/resolv.conf'
alias tunlr-off='cp /etc/resolv.conf.google /etc/resolv.conf'

alias wtc="curl -s -L http://whatthecommit.com/index.txt"

alias nocolor='sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"'
alias dfh='df -H'
alias dfh.='df -H .'

alias scana4='scanimage -d plustek:libusb:$(lsusb | grep -i scan | sed "s/Bus.\([0-9]*\).Device.\([0-9]*\).*/\1:\2/") -x 215 -y 297 --format=jpg --resolution=300'
alias scana5='scanimage -d plustek:libusb:$(lsusb | grep -i scan | sed "s/Bus.\([0-9]*\).Device.\([0-9]*\).*/\1:\2/") -x 215 -y 149 --format=jpg --resolution=300'

alias scancard='scanimage -d plustek:libusb:$(lsusb | grep -i scan | sed "s/Bus.\([0-9]*\).Device.\([0-9]*\).*/\1:\2/") -x 90 -y 55 --format=jpg --resolution=300'

alias nohistory='unset HISTFILE && history -c && hide'

# android
alias android-devicemanager="android avd"
alias android-sdkmanager="android sdk"

# compiler
alias cmake-arm="cmake -DCMAKE_TOOLCHAIN_FILE=~/projects/arm/toolchain.cmake -DCMAKE_INSTALL_PREFIX=/opt/arm -DQT_LRELEASE_EXECUTABLE=/usr/bin/lrelease"
