#!/bin/bash

#shortcuts
alias v='vim'
alias g='git'
alias m='mutt'
alias l='ls'
alias wq='clear'

alias qr='ttyqr -b'
alias vless='vimpager'

alias cd_='cd "$_"'
alias cdback='cd $OLDPWD'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

#params
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias rm="echo -n Delete\! CTRL-C to cancel, enter to delete\!;read&&rm"
alias whois='whois --verbose -H'
alias man='man -a'

#typos
alias namp='sl'
alias qw='sl'

#others
alias presentation="$TERMINAL -fn 'xft:DejaVu Sans Mono-15'"
alias presentation-white="$TERMINAL -fn 'xft:DejaVu Sans Mono-15' -bg white -fg black"

alias wifi-status="iwconfig 2>/dev/null|grep Signal|sed 's/^\s*//';[ \$? -ne 0 ]&&echo No Signal"
alias bmplayer="mplayer -ao alsa:device=bluetooth"
alias exif-remove-rotation="exiftool -overwrite_original -m -exif:Orientation=1 -n"

alias tunlr='cp /etc/resolv.conf.tunlr /etc/resolv.conf'
alias tunlr-off='cp /etc/resolv.conf.google /etc/resolv.conf'

alias wtc="curl -s -L http://whatthecommit.com/index.txt"

# android
alias android-devicemanager="android avd"
alias android-sdkmanager="android sdk"

