#!/bin/bash

. ~/.alias

function _timer_start {
  _timer=${_timer:-$SECONDS}
}

function _timer_stop {
  _timer_show=$(($SECONDS - $_timer))
  unset _timer
}

trap '__=$_; _timer_start; : "$__"' DEBUG
PROMPT_COMMAND='_timer_stop'

PS1='${_timer_show}:$?:\w\$ '

# Add color
if [[ $EUID -eq 0 ]]
then
  PS1="\[\033[0;91m\]$PS1\[\033[00m\]"
else
  PS1="\[\033[0;32m\]$PS1\[\033[00m\]"
fi

bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

shopt -s autocd
shopt -s checkwinsize


# This loads RVM into a shell session.
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
