#!/bin/bash

. ~/.alias

function _timer_start {
  _timer=${_timer:-$SECONDS}
  _idle_timer=${_idle_timer:-$SECONDS}
  let _timer_start_count+=1
}

function _timer_stop {
  _timer_show=$(($SECONDS - $_timer))
  _idle_timer_show=$(($SECONDS - $_idle_timer))

  if [ $_timer_start_count -eq 1 ]
  then
    _timer_show=$_idle_timer_show
  fi
  _idle_timer=${SECONDS}

  unset _timer
  unset _timer_start_count
}

trap '__=$_; _timer_start; : "$__"' DEBUG
PROMPT_COMMAND='_timer_stop'

PS1='${_timer_show}:$?:\w\$ '

# Add color
if [[ "$HOSTNAME" -eq "mt" ]]
then
  # local user
  if [[ "$EUID" -eq "0" ]]
  then
    # root: red
    PS1="\[\033[0;91m\]$PS1\[\033[00m\]"
  else
    # other: green
    PS1="\[\033[0;32m\]$PS1\[\033[00m\]"
  fi
else
  # remote user: blue
  PS1="\[\033[0;96m\]$PS1\[\033[00m\]"
fi

bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

shopt -s autocd
shopt -s checkwinsize

# function to show stderr in red
þ()(set -o pipefail;"$@" 2>&1>&3|sed $'s,.*,\e[31m&\e[m,'>&2)3>&1


# This loads RVM into a shell session.
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
